version: '3.4'

# services:
#   blinkpad:
#     image: blinkpad
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 5000:5000
services:
  blinkpad:
    build: 
        context: .
        dockerfile: ./Dockerfile
    command: python -u blinkpad.py
    ports:
      - "5000:5000"
    volumes:
      - .:/blinkpad
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=cluster0
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=drm8c5DszR7bipP
    volumes:
      # - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017